CREATE TABLE "bioskop" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar,
  "lokasi" varchar
);

CREATE TABLE "film" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "judul" varchar
);

CREATE TABLE "jadwal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_film" int,
  "id_bioskop" int,
  "tanggal" date,
  "jam_tayang" time,
  "jam_selesai" time
);

CREATE TABLE "kursi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_jadwal" int,
  "nomor_kursi" varchar,
  "is_available" bool
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar,
  "password" password
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int,
  "id_jadwal" int,
  "payment_status" varchar,
  "booking_date" datetime
);

CREATE TABLE "booking_kursi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_booking" int,
  "id_kursi" int
);

CREATE TABLE "transaksi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_booking" int,
  "total" decimal,
  "payment_date" datetime,
  "payment_method" varchar
);

ALTER TABLE "jadwal" ADD FOREIGN KEY ("id_film") REFERENCES "film" ("id");

ALTER TABLE "jadwal" ADD FOREIGN KEY ("id_bioskop") REFERENCES "bioskop" ("id");

ALTER TABLE "kursi" ADD FOREIGN KEY ("id_jadwal") REFERENCES "jadwal" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("id_jadwal") REFERENCES "jadwal" ("id");

ALTER TABLE "booking_kursi" ADD FOREIGN KEY ("id_booking") REFERENCES "booking" ("id");

ALTER TABLE "booking_kursi" ADD FOREIGN KEY ("id_kursi") REFERENCES "kursi" ("id");

ALTER TABLE "transaksi" ADD FOREIGN KEY ("id_booking") REFERENCES "booking" ("id");
